# Generated by Django 3.1.7 on 2021-04-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
